const QUESTION_TOPICS = [
    "Array",
    "String",
    "Hash Table",
    "Prefix Sum",
    "Sliding Window",
    "Two Pointers",
    "Intervals",
    "Palindrome",
    "Substrings and Subsequence",
    "Permutation",
    "Linked List",
    "Cycle Detection",
    "Stack",
    "Queue",
    "Set",
    "Tree",
    "Binary Tree",
    "Binary Search Tree",
    "Trie",
    "Graph",
    "DFS",
    "BFS",
    "Union Find",
    "Dynamic Programming",
    "Greedy",
    "Backtracking",
    "Binary Search",
    "Sorting",
    "Recursion",
    "Bit Manipulation",
    "Math",
    "Matrix",
    "Graph Traversal",
    "Topological Sort",
    "Data Structures",
    "Algorithms",
    "Databases",
    "Brainteaser"
];
  
export default QUESTION_TOPICS